- name: Download Bun install script
  ansible.builtin.get_url:
    url: https://bun.com/install
    dest: /tmp/install_bun.sh
    mode: "0755"

- name: Install Bun
  ansible.builtin.command: /tmp/install_bun.sh
