---
- name: Install Bun using official install script
  ansible.builtin.shell: |
    curl -fsSL https://bun.com/install | bash
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.SUDO_HOME | default(ansible_env.HOME) }}"
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
