---
- name: Download Bun
  get_url:
    url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
    dest: /tmp/bun.zip

- name: Install Bun
  unarchive:
    src: /tmp/bun.zip
    dest: "{{ ansible_env.SUDO_HOME }}/.bun/bin"
    creates: "{{ ansible_env.SUDO_HOME }}/.bun/bin/bun"

- name: Add Bun to PATH
  lineinfile:
    path: "{{ ansible_env.SUDO_HOME }}/.bashrc"
    line: 'export PATH="$HOME/.bun/bin:$PATH"'
    insertafter: EOF
