---
- name: Download nvm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
    dest: /tmp/install_nvm.sh
    mode: "0755"

- name: Install Node Version Manager (nvm)
  ansible.builtin.shell: /tmp/install_nvm.sh
  args:
    executable: /bin/bash

- name: Install Node
  ansible.builtin.command: "nvm install {{ node }}"
