---
- name: Enable Starship copr repo
  community.general.copr:
    name: atim/starship
    state: enabled

- name: Install Starship
  ansible.builtin.dnf:
    name: starship
    state: present

- name: Enable Starship for bash
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.SUDO_HOME }}/.bashrc"
    line: 'eval "$(starship init bash)"'
    insertafter: EOF
    state: present

# - name: Enable Starship for Fish
#   ansible.builtin.lineinfile:
#     path: "{{ ansible_env.SUDO_HOME }}/.config/fish/config.fish"
#     line: '\n#Starship\nstarship init fish | source'
#     insertafter: EOF
#     state: present

- name: Enable Nerd Fonts icons for Starship
  ansible.builtin.command: starship preset nerd-font-symbols -o {{ ansible_env.SUDO_HOME }}/.config/starship.toml
