---
- name: Enable Starship copr repo
  community.general.copr:
    name: atim/starship
    state: enabled

- name: Install Starship
  ansible.builtin.dnf:
    name: starship
    state: present

- name: Enable Starship for bash
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.SUDO_HOME }}/.bashrc"
    line: 'eval "$(starship init bash)"'
    insertafter: EOF

- name: Enable Nerd Fonts icons for Starship
  ansible.builtin.command: starship preset nerd-font-symbols -o {{ ansible_env.SUDO_HOME }}/.config/starship.toml
