---
- name: Import Microsoft GPG keys
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: true
    gpgcheck: true

- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    state: present

- name: Install VS Code extensions
  become: false
  ansible.builtin.command: code --install-extension {{ item }} --force
  loop:
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - adpyke.codesnap
    - naumovs.color-highlight
    - ms-azuretools.vscode-containers
    - ms-vscode-remote.remote-containers
    - icrawl.discord-vscode
    - usernamehw.errorlens
    - thang-nm.flow-icons
    - github.vscode-github-actions
    - GitHub.copilot
    - GitHub.copilot-chat
    - GitHub.github-vscode-theme
    - ms-vsliveshare.vsliveshare
    - PKief.material-product-icons
    - unifiedjs.vscode-mdx
    - johnpapa.vscode-peacock
    - esbenp.prettier-vscode
    - ms-vscode-remote.remote-ssh
    - ms-vscode.remote-explorer
    - wayou.vscode-todo-highlight
    - pflannery.vscode-versionlens
    - redhat.vscode-yaml

- name: Download VS Code settings
  ansible.builtin.get_url:
    url: "{{ vscode_settings }}"
    dest: "{{ ansible_env.SUDO_HOME }}/.config/Code/User/settings.json"
    mode: "0644"
    force: true
