---
- name: Edit DNF configuration
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      install_weak_deps=False
      max_parallel_downloads=10
      fastestmirror=True
    marker: "# {mark} DNF config (managed by Ansible)"
    insertafter: EOF
