---
- name: Remove fedora flatpak remote
  community.general.flatpak_remote:
    name: fedora
    state: absent

- name: Add flathub flatpak remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install common flatpak packages
  community.general.flatpak:
    name:
      - com.spotify.Client
      - com.github.tchx84.Flatseal
      - app.zen_browser.zen
      - it.mijorus.gearlever
      - com.github.unrud.VideoDownloader
      - eu.betterbird.Betterbird
      - io.gitlab.adhami3310.Impression
    state: present
