---
- include_tasks: dnf.yml
- include_tasks: update.yml
- include_tasks: rpmfusion.yml
- include_tasks: codecs.yml
- include_tasks: firmwares.yml
- include_tasks: packages.yml
- include_tasks: flatpak.yml
