---
- name: Import OnlyOffice GPG keys
  ansible.builtin.rpm_key:
    key: https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE
    state: present

- name: Install Onlyoffice repositorie
  ansible.builtin.dnf:
    name: https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm
    state: present

- name: Install OnlyOffice
  ansible.builtin.dnf:
    name: onlyoffice-desktopeditors
    state: present
