---
- name: Import Microsoft GPG keys
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: true
    gpgcheck: true

- name: Install VS Code
  ansible.builtin.package:
    name: code
    state: present

- name: Install VS Code extensions
  become: false
  ansible.builtin.command: code --install-extension {{ item }}
  loop:
    - astro-build.astro-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - adpyke.codesnap
    - naumovs.color-highlight
    - ms-azuretools.vscode-containers
    - ms-vscode-remote.remote-containers
    - icrawl.discord-vscode
    - imgildev.vscode-drizzle-snippets
    - usernamehw.errorlens
    - dsznajder.es7-react-js-snippets
    - dbaeumer.vscode-eslint
    - expo.vscode-expo-tools
    - thang-nm.flow-icons
    - github.vscode-github-actions
    - GitHub.copilot
    - GitHub.copilot-chat
    - GitHub.github-vscode-theme
    - golang.go
    - ms-vsliveshare.vsliveshare
    - PKief.material-product-icons
    - unifiedjs.vscode-mdx
    - quicktype.quicktype
    - johnpapa.vscode-peacock
    - esbenp.prettier-vscode
    - YoavBls.pretty-ts-errors
    - Prisma.prisma
    - AbianS.prisma-generate-uml
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.debugpy
    - ms-python.vscode-python-envs
    - ms-vscode-remote.remote-ssh
    - ms-vscode.remote-explorer
    - charliermarsh.ruff
    - rust-lang.rust-analyzer
    - bradlc.vscode-tailwindcss
    - tauri-apps.tauri-vscode
    - meganrogge.template-string-converter
    - wayou.vscode-todo-highlight
    - pflannery.vscode-versionlens
    - redhat.vscode-yaml

- name: Apply VS Code settings
  ansible.builtin.copy:
    src: https://gist.githubusercontent.com/wiizzl/4b221506171597a4eec703b8f0c23998/raw/config.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    remote_src: true
