---
- name: Import Microsoft GPG keys
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.acs
    repo_gpgcheck: true
    gpgcheck: true

- name: Install VS Code
  ansible.builtin.package:
    name: code
    state: present
